sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull omnetpp/travis-inet:5.3p2-180111

cache:
  directories:
    - $HOME/docker_ccache

# The "build" stage inherits this, so we won't have to repeat it 6 times.
# The "fingerprints" stage overwrites it for both of its jobs (only the .sh file is different).
script: docker run -ti --env TARGET_PLATFORM --env MODE --env TRAVIS_REPO_SLUG
          -v /home/travis/build/$TRAVIS_REPO_SLUG:/$TRAVIS_REPO_SLUG -v $HOME/docker_ccache:/root/.ccache
          omnetpp/travis-inet:5.3p2-180111 /bin/bash /$TRAVIS_REPO_SLUG/_scripts/travis/travis-stage-build.sh

# Note that the "env:" values must match EXACTLY (the whole string, even the spaces between the assignments)
# between the jobs in the "build" stage (which prepare the cache) and the corresponding jobs in the
# "fingerprints" stage (which use the cache). See: https://github.com/travis-ci/travis-ci/issues/9043
jobs:
  include:
    - stage: build
      env: TARGET_PLATFORM=linux MODE=release
    - env: TARGET_PLATFORM=linux MODE=debug
    - env: TARGET_PLATFORM=windows MODE=release
    - env: TARGET_PLATFORM=windows MODE=debug
    - env: TARGET_PLATFORM=macosx MODE=release
    - env: TARGET_PLATFORM=macosx MODE=debug

    - stage: fingerprints
      script: docker run -ti --env TARGET_PLATFORM --env MODE --env TRAVIS_REPO_SLUG
                -v /home/travis/build/$TRAVIS_REPO_SLUG:/$TRAVIS_REPO_SLUG -v $HOME/docker_ccache:/root/.ccache
                omnetpp/travis-inet:5.3p2-180111 /bin/bash /$TRAVIS_REPO_SLUG/_scripts/travis/travis-stage-fingerprints.sh
      env: TARGET_PLATFORM=linux MODE=release
    - script: docker run -ti --env TARGET_PLATFORM --env MODE --env TRAVIS_REPO_SLUG
                -v /home/travis/build/$TRAVIS_REPO_SLUG:/$TRAVIS_REPO_SLUG -v $HOME/docker_ccache:/root/.ccache
                omnetpp/travis-inet:5.3p2-180111 /bin/bash /$TRAVIS_REPO_SLUG/_scripts/travis/travis-stage-fingerprints.sh
      env: TARGET_PLATFORM=linux MODE=debug
